[parse]
sourcefile=[ "ngp.cpp" ]

[Pocket]
display_modes=[ 0x62, 0x63 ]

[ROM]
order = ["maincpu"]
firmware = "ngpc.rom"
carts =[ "ngp", "ngc" ]

# skip menu patch by angel_killah
patches=[ { offset=0x1bc6,data="""00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00"""} ]

[buttons]
names = [{names="A,B,Option"}]
